# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1069e0bea651a5e89cf2c1c3f06cdfd6"
name = "order tagger"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders_create"

[auth]
redirect_urls = [ ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
